# Generated by Django 3.0.1 on 2020-01-21 07:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupmapping',
            name='time_removed',
            field=models.DateTimeField(blank=True, default=users.models.end_date_time, null=True),
        ),
    ]
