# Generated by Django 3.0.1 on 2020-01-31 06:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algonautsuser',
            name='referal_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroupmapping',
            name='time_removed',
            field=models.DateTimeField(default=users.models.end_date),
        ),
    ]
