# Generated by Django 3.0.1 on 2020-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algonautsuser',
            name='algo_credits',
            field=models.IntegerField(default=0),
        ),
    ]
