# Generated by Django 3.0.1 on 2020-01-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algonautsuser',
            name='nick_name',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
