# Generated by Django 3.0.1 on 2020-01-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('user_group_type_id', 'admin')},
        ),
    ]
