# Generated by Django 3.0.3 on 2020-02-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfeedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='credits_granted',
            field=models.BooleanField(default=False),
        ),
    ]
