# Generated by Django 3.0.1 on 2020-01-31 06:46

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200131_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algonautsuser',
            name='referal_code',
            field=models.CharField(default=users.models.get_unique_referal_code, max_length=6, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
