# Generated by Django 3.0.1 on 2020-01-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_algonautsuser_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algonautsuser',
            old_name='contact',
            new_name='contact_no',
        ),
    ]
