# Generated by Django 3.0.1 on 2020-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouptype',
            name='max_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usergrouptype',
            name='min_members',
            field=models.IntegerField(default=1),
        ),
    ]
