# Generated by Django 3.0.2 on 2020-05-06 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_referral_credits_granted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=64)),
                ('line2', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', localflavor.in_.models.INStateField(max_length=2)),
                ('zipcode', models.CharField(max_length=12)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
