# Generated by Django 3.0.1 on 2020-01-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200131_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='algonautsuser',
            unique_together={('referal_code',)},
        ),
    ]
