# Generated by Django 3.0.2 on 2020-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='algonautsuser',
            name='allow_notification',
            field=models.BooleanField(default=False),
        ),
    ]
