# Generated by Django 3.0.1 on 2020-01-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200127_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algonautsuser',
            name='trail',
        ),
        migrations.AddField(
            model_name='algonautsuser',
            name='had_trial',
            field=models.BooleanField(default=False),
        ),
    ]
