# Generated by Django 3.0.1 on 2020-01-31 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200131_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraloffer',
            name='offer_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='offer_credits_by',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='offer_credits_to',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='offer_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='offer_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
