# Generated by Django 3.0.1 on 2020-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200117_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algonautsuser',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
