# Generated by Django 3.0.1 on 2020-01-21 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200118_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=128)),
                ('max_members', models.IntegerField()),
                ('min_members', models.IntegerField()),
                ('standard_group', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='algonautsuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserGroupMapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_added', models.TimeField()),
                ('time_removed', models.TimeField()),
                ('group_admin', models.BooleanField()),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user_group_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroupType'),
        ),
    ]
