# Generated by Django 3.0.1 on 2020-02-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200131_1707'),
        ('users', '0006_auto_20200131_1409'),
    ]

    operations = [
    ]
