# Generated by Django 3.0.1 on 2020-02-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200201_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referred_by', 'referred_to')},
        ),
    ]
