# Generated by Django 3.0.2 on 2020-05-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpush', '0002_auto_20190603_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgonautsPushInformation',
            fields=[
                ('pushinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpush.PushInformation')),
                ('allow_notification', models.BooleanField(default=False)),
            ],
            bases=('webpush.pushinformation',),
        ),
    ]
