# Generated by Django 3.0.2 on 2020-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgonautsPushInformation',
        ),
    ]
