# Generated by Django 3.0.2 on 2020-05-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpush', '0002_auto_20190603_0005'),
        ('worker', '0002_delete_algonautspushinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgonautsPushInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_notification', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algo_webpush_info', to='webpush.Group')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algo_webpush_info', to='webpush.SubscriptionInfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algo_webpush_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
