# Generated by Django 3.0.2 on 2020-05-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_algonautspushinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgonautsPushInformation',
        ),
    ]
