# Generated by Django 3.0.1 on 2020-01-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start', models.DateTimeField()),
                ('subscription_end', models.DateTimeField()),
                ('subscription_active', models.BooleanField()),
                ('payment_id', models.IntegerField(default=0)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Plan')),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup')),
            ],
        ),
    ]
