# Generated by Django 3.0.3 on 2020-02-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(default=None, max_length=20, null=True)),
                ('offer_start_date', models.DateTimeField()),
                ('offer_end_date', models.DateTimeField()),
                ('offer_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferPrerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(max_length=256)),
                ('payment_time', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=40)),
                ('price_per_month', models.PositiveIntegerField()),
                ('price_per_year', models.PositiveIntegerField()),
                ('entry_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('trial_applicable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfferMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64)),
                ('type_description', models.CharField(max_length=1024)),
                ('products_count', models.IntegerField(default=1)),
                ('trial_applicable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64)),
                ('duration_in_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start', models.DateTimeField()),
                ('subscription_end', models.DateTimeField()),
                ('payment_id', models.IntegerField(default=0)),
                ('is_trial', models.BooleanField(default=False)),
                ('subscription_active', models.BooleanField(default=False)),
                ('offer_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.Offer')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Plan')),
                ('subscription_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.SubscriptionType')),
            ],
        ),
    ]
