# Generated by Django 3.0.3 on 2020-02-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200218_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_amount', models.IntegerField()),
                ('order_currency', models.CharField(max_length=16)),
                ('order_receipt', models.CharField(max_length=1024)),
                ('notes', models.CharField(max_length=1024)),
                ('razorpay_payment_id', models.CharField(max_length=1024)),
                ('razorpay_order_id', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Order'),
        ),
    ]
