# Generated by Django 3.0.1 on 2020-01-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200129_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='offer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.Offer'),
        ),
    ]
