# Generated by Django 3.0.3 on 2020-02-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200224_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
