# Generated by Django 3.0.1 on 2020-01-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200129_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_active',
        ),
    ]
