# Generated by Django 3.0.1 on 2020-02-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
    ]
