# Generated by Django 3.0.3 on 2020-02-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20200225_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription_id',
        ),
    ]
