# Generated by Django 3.0.3 on 2020-02-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_subscription_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Payment'),
        ),
    ]
