# Generated by Django 3.0.5 on 2020-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20200228_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='razorpay_items_per_month_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_items_per_year_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
