# Generated by Django 3.0.5 on 2020-05-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20200430_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='razorpay_items_per_month_id',
            new_name='razorpay_plan_per_month_id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='razorpay_items_per_year_id',
            new_name='razorpay_plan_per_year_id',
        ),
    ]
