# Generated by Django 3.0.5 on 2020-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20200501_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
