# Generated by Django 3.0.5 on 2020-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscription_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
