# Generated by Django 3.0.1 on 2020-01-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=500)),
                ('price_per_month', models.PositiveIntegerField()),
                ('price_per_year', models.PositiveIntegerField()),
                ('entry_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AlgoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=200)),
                ('access_link', models.CharField(max_length=100)),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.AlgoProductCategory')),
            ],
        ),
    ]
