# Generated by Django 3.0.1 on 2020-01-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlgoProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=200)),
                ('access_link', models.CharField(max_length=100)),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.AlgoProductCategory')),
            ],
        ),
    ]
