# Generated by Django 3.0.1 on 2020-01-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200129_1357'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planproductmap',
            unique_together={('plan_id', 'product_id')},
        ),
    ]
