# Generated by Django 3.0.3 on 2020-02-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductfilter',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upf_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_product_category_id', to='products.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_product_family_id', to='products.ProductFamily'),
        ),
        migrations.AddField(
            model_name='planproductmap',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppm_plan_id', to='subscriptions.Plan'),
        ),
        migrations.AddField(
            model_name='planproductmap',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppm_product_id', to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='planproductmap',
            unique_together={('plan_id', 'product_id')},
        ),
    ]
