# Generated by Django 3.0.1 on 2020-01-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_subscription_active'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planproductmap',
            unique_together={('plan_id', 'product_id')},
        ),
    ]
